#!/bin/sh
#/etc/init.d/nodeup

export PATH=$PATH:/var/www/max/data/nodejs/bin
export NODE_PATH=$NODE_PATH:/var/www/max/data/nodejs/lib/node_modules

case "$1" in
  start)
  exec forever --sourceDir=/var/www/max/data/www/devconstruct.com/api/server -p /var/www/max/data/www/devconstruct.com/api/pids server.js
  ;;
stop)
  exec forever stop --sourceDir=/var/www/max/data/www/devconstruct.com/api/server server.js
  ;;
*)
  echo "Usage: /etc/init.d/nodeup {start|stop}"
  exit 1
  ;;
esac

exit 0

#gSa4Mt7K
